package interfaz;

import java.io.File;
import java.sql.Connection;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JRDataSource;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperExportManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.data.JRBeanCollectionDataSource;

/**
 *
 * @author Shaila
 */
public class JDialogoInformes extends javax.swing.JDialog {

    static String seleccionUnidadGuardarInforme;
    private Connection connection;
    private File carpetaInformes;
    /**
     * Creates new form JDialogConfirmacionTweet
     */
    private long id;

    public JDialogoInformes(java.awt.Dialog parent, boolean modal) {
        super(parent, modal);
        initComponents();
        //parent.dispose();//cerramos al padre una vez entrado
        setLocationRelativeTo(null);
        //Establecer el título de la aplicación
        setTitle("TTCSASM");
        jButtonInforme1.setEnabled(false);
        jButtonInforme2.setEnabled(false);
        jButtonInforme3.setEnabled(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCalendar1 = new com.toedter.calendar.JCalendar();
        jPanelHeader = new javax.swing.JPanel();
        jPanelHeader1 = new javax.swing.JPanel();
        jButtonInforme3 = new javax.swing.JButton();
        jButtonSeleccionarCarpeta1 = new javax.swing.JButton();
        jButtonInforme2 = new javax.swing.JButton();
        jButtonInforme1 = new javax.swing.JButton();
        jLabelSeleccionarInforme = new javax.swing.JLabel();
        jLabelSeleccionarCarpeta1 = new javax.swing.JLabel();
        jLabelSeleccionarInforme1 = new javax.swing.JLabel();
        jLabelSeleccionarInforme2 = new javax.swing.JLabel();
        jTextFieldUsuario = new javax.swing.JTextField();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jLabelSeleccionarInforme3 = new javax.swing.JLabel();
        jButtonSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanelHeader.setBackground(new java.awt.Color(255, 255, 255));
        jPanelHeader.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Informes", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 16))); // NOI18N
        jPanelHeader.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelHeader1.setBackground(new java.awt.Color(56, 161, 243));
        jPanelHeader1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Twitter", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 16))); // NOI18N
        jPanelHeader1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonInforme3.setBackground(new java.awt.Color(255, 255, 255));
        jButtonInforme3.setForeground(new java.awt.Color(56, 161, 243));
        jButtonInforme3.setText("Informes tweets usuario");
        jButtonInforme3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInforme3ActionPerformed(evt);
            }
        });
        jPanelHeader1.add(jButtonInforme3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 240, 210, -1));

        jButtonSeleccionarCarpeta1.setBackground(new java.awt.Color(255, 255, 255));
        jButtonSeleccionarCarpeta1.setForeground(new java.awt.Color(56, 161, 243));
        jButtonSeleccionarCarpeta1.setText("Seleccionar carpeta...");
        jButtonSeleccionarCarpeta1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSeleccionarCarpeta1ActionPerformed(evt);
            }
        });
        jPanelHeader1.add(jButtonSeleccionarCarpeta1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 40, 180, -1));

        jButtonInforme2.setBackground(new java.awt.Color(255, 255, 255));
        jButtonInforme2.setForeground(new java.awt.Color(56, 161, 243));
        jButtonInforme2.setText("Informe tweets por fecha");
        jButtonInforme2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInforme2ActionPerformed(evt);
            }
        });
        jPanelHeader1.add(jButtonInforme2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 180, 210, -1));

        jButtonInforme1.setBackground(new java.awt.Color(255, 255, 255));
        jButtonInforme1.setForeground(new java.awt.Color(56, 161, 243));
        jButtonInforme1.setText("Informes Follows & Followers");
        jButtonInforme1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInforme1ActionPerformed(evt);
            }
        });
        jPanelHeader1.add(jButtonInforme1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 120, 210, -1));

        jLabelSeleccionarInforme.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabelSeleccionarInforme.setText("Introduzca un usuario:");
        jPanelHeader1.add(jLabelSeleccionarInforme, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 170, 20));

        jLabelSeleccionarCarpeta1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabelSeleccionarCarpeta1.setText("Seleccione una carpeta:");
        jPanelHeader1.add(jLabelSeleccionarCarpeta1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 36, 180, 20));

        jLabelSeleccionarInforme1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabelSeleccionarInforme1.setText("Seleccione un informe:");
        jPanelHeader1.add(jLabelSeleccionarInforme1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 180, 20));

        jLabelSeleccionarInforme2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabelSeleccionarInforme2.setText("y");
        jPanelHeader1.add(jLabelSeleccionarInforme2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 20, 20));
        jPanelHeader1.add(jTextFieldUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 240, 210, -1));
        jPanelHeader1.add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));
        jPanelHeader1.add(jDateChooser2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, -1, -1));

        jLabelSeleccionarInforme3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabelSeleccionarInforme3.setText("Seleccione dos fechas:");
        jPanelHeader1.add(jLabelSeleccionarInforme3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 180, 20));

        jPanelHeader.add(jPanelHeader1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 650, 300));

        jButtonSalir.setBackground(new java.awt.Color(255, 255, 255));
        jButtonSalir.setForeground(new java.awt.Color(56, 161, 243));
        jButtonSalir.setText("Salir");
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });
        jPanelHeader.add(jButtonSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 340, 180, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 714, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanelHeader, javax.swing.GroupLayout.DEFAULT_SIZE, 690, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 422, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanelHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonInforme3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInforme3ActionPerformed

        
        try {
            //Obtenemos la lista a mostrar
            List<User> listaFollows = new ArrayList<>();
            List<User> listaFollowers = new ArrayList<>();

//Falta meterlo en la lista que vamos a mandar al Ireport
            List<User> listas = new ArrayList<>();
//La encapsulamos en el objeto adecuado
            JRDataSource dataSource = new JRBeanCollectionDataSource(listas);

//Creamos el map para los parámetros, en este caso va vacío.
            Map parametros = new HashMap();
            JasperPrint print = JasperFillManager.fillReport(
                    "informe3.jasper", parametros, dataSource);

            JasperExportManager.exportReportToPdfFile(print, carpetaInformes.
                    getAbsolutePath() + File.separator + "Informe3.pdf");

        } catch (JRException ex) {
            System.out.println(ex.getMessage());
        }
        this.dispose();
        JOptionPane.showMessageDialog(this, "Se ha generado el informe satisfactoriamente.",
                "Informe 3.", JOptionPane.INFORMATION_MESSAGE);
  
        
    }//GEN-LAST:event_jButtonInforme3ActionPerformed

    private void jButtonSeleccionarCarpeta1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSeleccionarCarpeta1ActionPerformed

        try {
            //Obtenemos la lista a mostrar
            List<User> listaFollows = new ArrayList<>();
            List<User> listaFollowers = new ArrayList<>();

//Falta meterlo en la lista que vamos a mandar al Ireport
            List<User> listas = new ArrayList<>();
//La encapsulamos en el objeto adecuado
            JRDataSource dataSource = new JRBeanCollectionDataSource(listas);

//Creamos el map para los parámetros, en este caso va vacío.
            Map parametros = new HashMap();
            JasperPrint print = JasperFillManager.fillReport(
                    "informe2.jasper", parametros, dataSource);

            JasperExportManager.exportReportToPdfFile(print, carpetaInformes.
                    getAbsolutePath() + File.separator + "Informe2.pdf");

        } catch (JRException ex) {
            System.out.println(ex.getMessage());
        }
        this.dispose();
        JOptionPane.showMessageDialog(this, "Se ha generado el informe satisfactoriamente.",
                "Informe 2.", JOptionPane.INFORMATION_MESSAGE);
  

    }//GEN-LAST:event_jButtonSeleccionarCarpeta1ActionPerformed

    private void jButtonInforme2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInforme2ActionPerformed

        try {
            //Obtenemos la lista a mostrar
            List<User> listaFollows = new ArrayList<>();
            List<User> listaFollowers = new ArrayList<>();

//Falta meterlo en la lista que vamos a mandar al Ireport
            List<User> listas = new ArrayList<>();
//La encapsulamos en el objeto adecuado
            JRDataSource dataSource = new JRBeanCollectionDataSource(listas);

//Creamos el map para los parámetros, en este caso va vacío.
            Map parametros = new HashMap();
            JasperPrint print = JasperFillManager.fillReport(
                    "informe2.jasper", parametros, dataSource);

            JasperExportManager.exportReportToPdfFile(print, carpetaInformes.
                    getAbsolutePath() + File.separator + "Informe2.pdf");

        } catch (JRException ex) {
            System.out.println(ex.getMessage());
        }
        this.dispose();
        JOptionPane.showMessageDialog(this, "Se ha generado el informe satisfactoriamente.",
                "Informe 2.", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jButtonInforme2ActionPerformed

    private void jButtonInforme1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInforme1ActionPerformed

    }//GEN-LAST:event_jButtonInforme1ActionPerformed

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonSalirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonInforme1;
    private javax.swing.JButton jButtonInforme2;
    private javax.swing.JButton jButtonInforme3;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JButton jButtonSeleccionarCarpeta1;
    private com.toedter.calendar.JCalendar jCalendar1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabelSeleccionarCarpeta1;
    private javax.swing.JLabel jLabelSeleccionarInforme;
    private javax.swing.JLabel jLabelSeleccionarInforme1;
    private javax.swing.JLabel jLabelSeleccionarInforme2;
    private javax.swing.JLabel jLabelSeleccionarInforme3;
    private javax.swing.JPanel jPanelHeader;
    private javax.swing.JPanel jPanelHeader1;
    private javax.swing.JTextField jTextFieldUsuario;
    // End of variables declaration//GEN-END:variables

}
