package interfaz;

import java.awt.Image;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.io.File;
import java.io.IOException;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import logica.GestionClienteTwitter;
import twitter4j.Status;
import twitter4j.Twitter;
import twitter4j.TwitterException;

/**
 *
 * @author Shaila
 */
public class VistasBusqueda extends javax.swing.JDialog {

    private Twitter twitter;
    private DefaultListModel statuses = new DefaultListModel();

    /**
     * Creates new form User
     */
    public VistasBusqueda(java.awt.Dialog parent, boolean modal, final Twitter twitter) {
        super(parent, modal);
        initComponents();
        //parent.dispose();//cerramos al padre una vez entrado
        setLocationRelativeTo(null);
        //Establecer el título de la aplicación
        setTitle("TTCSASM");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelBackground = new javax.swing.JPanel();
        jPanelTL = new javax.swing.JPanel();
        jScrollPaneHomeTL = new javax.swing.JScrollPane();
        jListContenidoBúsqueda = new javax.swing.JList<>();
        jLabelBusqueda = new jlabeltt.JLabelTT();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelBackground.setBackground(new java.awt.Color(244, 244, 244));
        jPanelBackground.setPreferredSize(new java.awt.Dimension(600, 200));

        jPanelTL.setBackground(new java.awt.Color(255, 255, 255));

        jScrollPaneHomeTL.setBackground(new java.awt.Color(255, 255, 255));

        jListContenidoBúsqueda.setModel(statuses);
        jListContenidoBúsqueda.setCellRenderer(new Tweet(twitter));
        jScrollPaneHomeTL.setViewportView(jListContenidoBúsqueda);

        jLabelBusqueda.setText("Búsqueda");
        jLabelBusqueda.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N

        javax.swing.GroupLayout jPanelTLLayout = new javax.swing.GroupLayout(jPanelTL);
        jPanelTL.setLayout(jPanelTLLayout);
        jPanelTLLayout.setHorizontalGroup(
            jPanelTLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTLLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPaneHomeTL, javax.swing.GroupLayout.DEFAULT_SIZE, 632, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanelTLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelTLLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabelBusqueda, javax.swing.GroupLayout.DEFAULT_SIZE, 632, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanelTLLayout.setVerticalGroup(
            jPanelTLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTLLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jScrollPaneHomeTL, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
            .addGroup(jPanelTLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelTLLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabelBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(184, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout jPanelBackgroundLayout = new javax.swing.GroupLayout(jPanelBackground);
        jPanelBackground.setLayout(jPanelBackgroundLayout);
        jPanelBackgroundLayout.setHorizontalGroup(
            jPanelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBackgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelTL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelBackgroundLayout.setVerticalGroup(
            jPanelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBackgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelTL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        getContentPane().add(jPanelBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 260));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pintarTimeLine(Twitter twitter) {

        for (Status status : GestionClienteTwitter.listarTimeLineUsuario(twitter)) {
            statuses.addElement(status);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private jlabeltt.JLabelTT jLabelBusqueda;
    private javax.swing.JList<String> jListContenidoBúsqueda;
    private javax.swing.JPanel jPanelBackground;
    private javax.swing.JPanel jPanelTL;
    private javax.swing.JScrollPane jScrollPaneHomeTL;
    // End of variables declaration//GEN-END:variables
}
