package interfaz;

import java.awt.Component;
import java.awt.Image;
import java.io.File;
import java.io.IOException;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.help.HelpBroker;
import javax.help.HelpSet;
import javax.help.HelpSetException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JList;
import javax.swing.ListCellRenderer;
import twitter4j.Twitter;
import twitter4j.User;
import utils.Fecha;

/**
 *
 * @author Mario
 */
public class VistaUser extends javax.swing.JPanel implements ListCellRenderer<Object> {

    /**
     * Creates new form Tweet
     */
    public VistaUser() {
        initComponents();
    }

    /**
     * Método que incorpora la ayuda en nuestro proyecto.
     */
    private void ponLaAyuda() {
        try {
            //Carga el fichero de ayuda
            File fichero = new File("help" + File.separator + "help_set.hs");
            URL hsURL = fichero.toURI().toURL();

            //Si metemos la carpeta help en src tenemos que quitar lo anterior y poner
            /**
             * URL ayuda = getClass().getResource("ruta"); File
             * ficheroAyudaEnJar = new File(ayuda.toURI());
             */
            //Crea el HelpSet y el HelpBroker
            HelpSet helpset = new HelpSet(getClass().getClassLoader(), hsURL);
            HelpBroker hb = helpset.createHelpBroker();

            /**
             * Pone ayuda a item de menu al pulsarlo y a F1 en ventana ppal y
             * secundaria.
             */
            //hb.enableHelpOnButton(jMenuItemAyuda, "aplicacion", helpset);
            //Al pulsar F1 salta la ayuda
            
            hb.enableHelpKey(getRootPane(), "aplicacion", helpset);
            // Pone ayuda a item de menu al pulsarlo y a F1 en ventana
            // principal y secundaria.

        } catch (MalformedURLException ex) {
            System.out.println(ex.getMessage());
        } catch (HelpSetException ex) {
            System.out.println(ex.getMessage());
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelBackground = new javax.swing.JPanel();
        cLabelAvatar = new jlabelcircular.CLabel();
        jLabelTTScreenName = new jlabeltt.JLabelTT();
        jLabelDate = new javax.swing.JLabel();
        jLabelFollowers = new javax.swing.JLabel();
        jLabelTweets1 = new javax.swing.JLabel();
        jLabelFollows = new javax.swing.JLabel();
        jLabelFollowsCount = new javax.swing.JLabel();
        jLabelFollowersCount = new javax.swing.JLabel();
        jLabelTweetsCount = new javax.swing.JLabel();

        jPanelBackground.setBackground(new java.awt.Color(255, 255, 255));

        cLabelAvatar.setBackground(new java.awt.Color(255, 255, 255));
        cLabelAvatar.setLineBorder(4);
        cLabelAvatar.setLineColor(new java.awt.Color(56, 161, 243));

        jLabelTTScreenName.setText("ScreenName");
        jLabelTTScreenName.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N

        jLabelDate.setText("Date");

        jLabelFollowers.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelFollowers.setText("Followers");

        jLabelTweets1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelTweets1.setText("Tweets");

        jLabelFollows.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelFollows.setText("Follows");

        jLabelFollowsCount.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelFollowsCount.setText("Follows");

        jLabelFollowersCount.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelFollowersCount.setText("Followers");

        jLabelTweetsCount.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelTweetsCount.setText("Tcount");

        javax.swing.GroupLayout jPanelBackgroundLayout = new javax.swing.GroupLayout(jPanelBackground);
        jPanelBackground.setLayout(jPanelBackgroundLayout);
        jPanelBackgroundLayout.setHorizontalGroup(
            jPanelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBackgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cLabelAvatar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelBackgroundLayout.createSequentialGroup()
                        .addComponent(jLabelTTScreenName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelDate))
                    .addGroup(jPanelBackgroundLayout.createSequentialGroup()
                        .addComponent(jLabelTweetsCount)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelFollowersCount)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelFollowsCount))
                    .addGroup(jPanelBackgroundLayout.createSequentialGroup()
                        .addComponent(jLabelTweets1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelFollowers)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelFollows)))
                .addContainerGap(153, Short.MAX_VALUE))
        );
        jPanelBackgroundLayout.setVerticalGroup(
            jPanelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBackgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelBackgroundLayout.createSequentialGroup()
                        .addGroup(jPanelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelTTScreenName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelDate))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelTweets1)
                            .addComponent(jLabelFollowers)
                            .addComponent(jLabelFollows))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelTweetsCount)
                            .addComponent(jLabelFollowersCount)
                            .addComponent(jLabelFollowsCount)))
                    .addComponent(cLabelAvatar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelBackground, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private jlabelcircular.CLabel cLabelAvatar;
    private javax.swing.JLabel jLabelDate;
    private javax.swing.JLabel jLabelFollowers;
    private javax.swing.JLabel jLabelFollowersCount;
    private javax.swing.JLabel jLabelFollows;
    private javax.swing.JLabel jLabelFollowsCount;
    private jlabeltt.JLabelTT jLabelTTScreenName;
    private javax.swing.JLabel jLabelTweets1;
    private javax.swing.JLabel jLabelTweetsCount;
    private javax.swing.JPanel jPanelBackground;
    // End of variables declaration//GEN-END:variables

    @Override
    public Component getListCellRendererComponent(JList<? extends Object> list, Object value, int index, boolean isSelected, boolean cellHasFocus) {
        try {
            User user = (User) value;
            jLabelTTScreenName.setText("@" + user.getScreenName());

            Image image;

            image = ImageIO.read(new URL(user.getBiggerProfileImageURL())).getScaledInstance(cLabelAvatar.getWidth(),
                    cLabelAvatar.getHeight(), Image.SCALE_SMOOTH);
            cLabelAvatar.setIcon(new ImageIcon(image));

            jLabelDate.setText(Fecha.timeFormat(user.getCreatedAt()));
            
            jLabelFollowersCount.setText(user.getFollowersCount()+"");
            jLabelFollowsCount.setText(user.getFriendsCount()+"");
            jLabelTweetsCount.setText(user.getStatusesCount()+"");
            
            return this;
        } catch (MalformedURLException ex) {
            Logger.getLogger(VistaUser.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(VistaUser.class.getName()).log(Level.SEVERE, null, ex);
        }
        return this;
    }
}
